---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ordenes-secreto
  namespace: sa-p8
spec:
  encryptedData:
    DATABASE_URL: AgCv10Ka35fNTG8VwSwvI4tEGo8zWi7WgrzHxfir9JGq2XIMEgOpGCX510O9uTc6VwURtqqnTHIbm0WgSqQvpGVHrEafZWVBYm4AoM8qWVnZ4Po2i5sDj/CsqVyvtSaapMQrZSgibnAXZdNN5O8RiBOs1uZZN8PpWwY526IABLQi8mPIUGiYpW0hQajZZ+pVhetR7RKwOyCCkL3/L1A9/qJn2/TEj9vu7D2Gs/huDcfAkgTnK5ZrES9eGcC9RkHATngqzWOBdFEewC4HD//IWB/ESv9/nAC+4L2E9sV+RhzZsXLHXcCAHuaFoNswhXQfwPvD1xdaJanbaqhUGTwwAqZ16EiW7onY/HA903L6ipHsu9m15Jyp4cj/OfSZBwyoOyTxAqHinBUPiPDcUjCggQkz3bZKW47Ss1KMPgmUiUtQ52edAwpAxN3A84WWovbthz2/qR7ltMWSVdyeMO0Ic6K5YcmqV5TvS0BC4F+9gg/SVRfgiwN+4i1U/iW0oMLrQRgxlo34fhyeEn6O5yXJ9zEHfX7K06vMJnIrM3OsS18L0yYkSlK/AzcTkZR/64hEbhfSpJ9hYxMwBMK4W+EpFQoRMfB+cgmIy6HuPQACFJHcc+2v+on4wutl6AYAfDcTUcxpXVMebMpxgio+rxoPFx/THTtmNvZQvEQHmHWz7StDQc6H1K01WbvH34Sfkr2ddVKDaz02PjzXBnJvlUSI4YWXTeB+81rueS8xZi8l8ZoUYD4f0XJ2MBsq09qE0GKcniuyIP3d5CQIGhM9Cg0WlRlfpzIlas6pa/Ok8P9Lt1je9e5XgNDcHpBM1eynW0ZtNA==
    RABBITMQ_URL: AgCbbyFl4Zr3w0OI9hLItgvgsIpIl8cVd/PAH5jxVYgKi2IEwLMyu1W0ClBeUheObJutYEmFeoOB07/T8UmVqNudfXED0l0/aHsNHwtMgndhSNmC2yQ+P4QZ3kpCPoVbal/pF3xEx0IXWq998/HySP1M28gR/ku2DA3q2w/ejoYZrUOCUKfNUGhO4oDbG5HZfdRqHRYFcVchvz7XUtNZSpOwlKYQyW1+ENjHMV3sNlcJ7RiRjiDp/DbX6kr8rwwh3fzXz4gRMdkpJ7cLV3qe+XzkoKdzzpbKnPNVib52VSI1VpBu+25a9NHInN+BML9fu4RVcxwt9bxQeuwjTOxK0iXE/2A9PLM8kvcj8T2AIUUphTCahakppdjkbb0rwZ1ohg5MFXbN2mpifwFiPQX6L0Y7jA96idzH4m3bKHfVQIBzUjPrg/iDCNC7PJ54ZKzHj61o8iq0HucmEhr6ELpvisJCQkZNU1d1qOSe79YlJ4MHbozh6bD6Im8JYPJ3Y4ne6409RvhSPowWCCCKjRMhGtkWWbj+hmOCRNld7GUPnsjuH6ME+Bx0HZWR5Sd8mnKUC+M0GfIXhVNrlYHYesvl2ThG4TqwDBBhmOcbwEUHiVaBJqagvbBzRdYK0P8nPdbtsFvriYzEyg9ndKwIEavwJhJe6e/9Ag0Kx3qH2VJzRPVSUjYkqGd6YChtRlbRzZiNe9qNQNUptRhk8J5uKYefsdTYthE6XqGCAdM2pnSQGzrmbxYUkcMFwJVzgA9r3m6ZVx0L20UJOfupOApGH2232f8NOozp5863NbRP/6A=
  template:
    metadata:
      name: ordenes-secreto
      namespace: sa-p8
    type: Opaque
