---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secreto
  namespace: sa-p8
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAQzqwMyQWIWqRSXNzA8FJvpe9vaQoPKNt1cz1TsuBTBSsbvBpPDBSKZeY3cMosE1hH+1j8HZqH8NobFzOGdsV1aTm3jRsDnJoJVQ/vcoPUn+VeRcpFWmr8t7AIOB/7QtY5KC+2JfYzsEh+wrbADjvNqpl1pqoMNBKz/1hEUQ/bZb6tt5pzhIDk+qn1Xj5hf9CgRZuGo4mdCftG+/aBXo4wH5Yg2SjvQymlXm8ACnG7yhI/MJW0SN6ChPjfIt85bnoU4LP+rUsWkNH6kb3Hrmjntqq1A7DyLy24RuUTRFTqLwnfIeaGrMuTW42b25PqMWrhPu+7jO3iqibw+wXP6EZVKjwH5IOuIm3nS+pivk/72HWmUB4aN3fo2QDfMvRO5KAlpoUXDrzuLnf+f8CpXEGmYjhZyisX8BfexeLfZYPeJ+2Dkgjn6j522Pqugs+OLX4cx52xQVXOndRVtysoKmt6Mz3MGRc+5szZgYWEFBa/d9zCxhVsSAL8zOlXeLTbGHVWKGwfisXA3Zvxu5LqyvA8gXRqsatMxei7kjP7vP0l3wnAcbqtmxCNyH/tTa+iNbQWGdLLE8AxWX+6Cz8gCM0davX9er7nvEaqMIoB7Pp/w2QRTSD7Di1gW7DE7eZvKnwN1IqSvJ8VU2UZ/D1MKnyDKSIJPPthZ4dhVwmRFwCfUbWwsA0dWNBPcx63LmdRcIkvS4mA+A0/9yNnleqfgjPM0KrtV6zmu1v5NxsO33XGPeEwB79+xAtD+lXV72kUSlU=
    POSTGRES_USER: AgCcB9ioMc4OvkzOsq3VEzkqwBAGeHXp8XM4/j8nJg2V+VKiZMjcCDNQ2gSSDMWJyJmHHtG5Lo+6KBiTrc1V5b70j5ZHFfSW3BdB+jWHAyRj2EmhQ9rCCCw3r3rB7W/AvZ2jGWMigUleYR/lAy4b0LLIrzagQUBcenjsCTm+nJN8y/Wd14GoQ2YmUCxnnHF7lwJXtr73GmHTr3g2au0elen9cbkarQmzmBOeAxBqAhQ4zKVopvNpXfdql4Le6Zrr/DKGEjdyDFTkd9elFuQoNnuT4KK8AvEaspIXzfNa+5HXEubskAWg1V0IE81wetogWemCFxogAOLD6BffGJ+UG5k86Ir0Jzt4fNGtb1oaYDgx7Bonn9ya5sq3kW/kpCN5/51TNdg3raW5jgRbpLQ1RgxvU7aNpymHwvs19xVjAwCsWItrsvgFhwB5B491eY3dp7WZwklFgElffyDbwGIvs2ZAgjFIPW7eQURvHKao7wQ5DwyjMjeh9n206QYwTrnsSK47GTqA3oTlr780h1MKj+2WGj9KGEFENTsyvL6oERZ1f29hUIh+yiAlsE77QYS9Z3Bbdq+8fxd3hS9nmrEU4nOGmEMwJM+c21ZHzYePnggiZAJ8f1CPY4Vro0B1ZM48aoLic2nhcwWBuzl9acg8IVqWZEKv9Uzuw7R5YVsDWhPdR/mP9hf3Z/wGOn/EiwWfZuST4ioWa087tQ==
  template:
    metadata:
      name: postgres-secreto
      namespace: sa-p8
    type: Opaque
