---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secreto
  namespace: sa-p8
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgAFeTDTJd9LAOSpxFJp6v4gsIhcrX8RFGVczJwhC/VAq1OSBQzxZGwoscfSU/sQB39tZTnyZt9ZTydS/PrM+iH9peaKu3+nCz7OSgNEssNztq0u1ImfaB4AGx1YN1KlKXAvZy3Yh5UdMoorqwbbiur9u3LkS4IuwphBrG0xfA8MrbwwTFzRQuDCtTZ+Dq+QtNHxhtePZUzJqziTtZ7YstldwdbsqyTl5k69DMk/TdlLrZHUnFARZRwnQ8kHzM5Y3pbQdtw+sOvvHBNmwjQsg6J6SHArxtV0tgQGUG7PQfCeG7aNBuKONMF/O5GdsiT28uR/sTnKiMxFxxGHBxDeRZ1YbwiDciMEIfYCUSbAqTMMQmObLTFXljNz1j21gOyngYhUZm5kMsq6PTb/9RxhEcJRn1Q2eRc7Zl6OPIsyertLJHhNtQku2bl8lzLCUYq2QeACfB56mJGyFBc01ol6Twe/k08h2gSwxmeHtjpftHPjOUKSbOBDRpgBo+8Nb3uvoKNHSEnBt/s5PFdPtxe+36t1btnffuhV3bPyZYLtsRT3zHZ2aNhxfrp17rmSGy8Q3UN+8yZ9B8EDk8RyboIiFwXTJrvFKdT3KdugoJVGZ9xnkoEgEgvATMGNWrSphBfKWCaLWjMaNgkFJIgdYiv/Bdgs6hPnf/2lIYz+hYp2cIaaxQuUyuu86HtDnBsiDvhu6eCWeZdLCn1lSggOrAQ2PPIF0VrDSAwHH/scwTTqeSlxaL4QP5glJgc30IGIpRywuqX1q6JxNBEAajTw0NldhrHo
    rabbitmq-password: AgBaQJBVhH7bjv/luTGz3LbAdIwf9yqolZKAZpmYNIh2UuYRPLFZKB77WoMfO6wqh0GdV+E1/889trpEqcp34Ql/ZY7DbSeH9NlAVrkNNps/zqntLhqCmDhETVXBzF3vtxna14NwZBciOxfPdWSYPud3+DCO9YbbGmiQx3+QPLIclmNDfcU+atqBTXyx9sbC0JbmGX/0b4xmz0iwI+R2dnr7uyL1NbIVTlL2PiukCfXPwHOsnjZPTnsJBiIX2hVlA86jzz4vaTv86kQMl03LoazyDQIXOOwubeSTSqh6qud9QgcpUMAs6AfRZyHmGYoeUppBkLmsKq5YzWF/JfcOi6UkfYhK2UTFIDzW1q1LZuoIXJBSHk3/gO1Vvw8VGu6Bc5lmruupYiipe6RY+spaDJu2E3aj51Rxq8ZfWSAToKOQ65lifRvw8otPMgGpIJ2eR3pxOnw/nd3ikNAqamz0znVeKaWYe6Bpb7DzdOVAotcryoCndMAu1d4EF9V0e18PDHg0x+UVeOFRHwHPJy3PiD0H8zpMusfPpcr0MKmoechNmOVCq0xIkkJl81qvCmCjRD+Ss4MWxK4xfvjCp1ASANaTwOIO6OPMTJd5E8s3fzVYDoLCp23q3nVZ132D2hpono9YPbj2HSqboJELxTiPSgK/M0+kpXjtWkqvlepYq/ckWLsxWejxuYF9iV1K4SwtsfRLpHTCjsQk/ydKNnLZ+0i5owTg1KBORlKSmnz6HOKYdAY5yEB27/v91DDmoG0EKLE=
  template:
    metadata:
      name: rabbitmq-secreto
      namespace: sa-p8
    type: Opaque
