---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: resumen-secreto
  namespace: sa-p8
spec:
  encryptedData:
    DATABASE_URL: AgBCPCGALLefW3mHuaA0m3tIZZXSmcXhX8s2YMlvdt/mLWUHIkroTRKhDh2Uj/N4twWRdytfrF0j0/wAlAT7JDM4Xop+hUu72wsCCeXld+KyVmsMi8XLaJMqYcu8klHr9let/WJElaU87WVO7x4gSOEMvamQGNdFiBlALHHKyX0EQSZzEkIet6FAuVfW+CzJtx9HKOP8Z+KmhzL1/lU82MizJMi/uNAfJtgt/LfJqlf58rpU8K8hf7C4LniqOWkKd885ADvAOHXUK+k7+qDRWOQLxowLhUUXkzeiiiFL6YRdLJz065c5Jj6VxionVm5QUZi6i2ciqtTxvhMZeZK6DY94cXukg+vuRCB8n4UQV5HVtjF4v7LyFOiOKs8LejNZv5QOmqXtCjBZspYPb8LUAvuGEJVZP29LqEVoKhtdByMPAwkHbfCEXGsxCxI2B/+KHWmB0iHc4IGzKvB7M5I24PhN0X29qsd0XRiJ0Zli8FxERCwSNqIJeQkgy8jd89LFYXLhjLkmbaviUd3NJdE3YF7YyKn1CUjd9lj8pzVsUfqUz8oZ/kZKZOjpXW3fvcJTr3ioaMwg4l7mS4co2TxD2KqoajrzhltPgcMuCbXGBV2bZvg0FBQ9dgg++7bMoIusDO6Cx1ds21RIaDTtPr/bnr8YEtKu81VEiPne4v/CqaVI5dsl9gxvu4KBU3pYGWFEKWBQ+u2H430LKKJ1z5J9FoCFhmmwJeXfOQl2XyTWT/rvsOowTQaCe+fuyyHkgwYWTUE80Rps57XQLnnwMcmVBj4CA0p2naGRC+b2uFlOscbvhmQwk+Dj6/ZykEHOpUi74sM=
    RABBITMQ_URL: AgAUIh2jfye2hKrfJXiTTIXhLsDtBmrnQNNsQowFxW8S+vGo5UvV4KHZBujkdDIYcY3KXupxk+aCsGCvN+qhMRwvtIpfI6+i4FagNZTLhfIlBVQ5qiR+qtGFw6RsG/W1ii7PSgRUjE7cJpL/+sBCzgkmwCUPZEdc09wlSUfcl2EUSNib3n+uFEBMaa0ws8CHAQkzaJtNHRGlxJrB3U8xwsUrGOc5QwtlMBxzvc0we4mOkFm2FZS5kZTQL/s0i84iZ/jkFneQWeNTUiuqKdOJnO27rtcfVuRscaEHJ832c2ALqCTS5gwPGgeFR66fjpHwEv5KMXkXNvvIqeJ0Adv6DJTRDaGcQe3LEozCI69iZBZWIrh0nSM24+i4voUSt+Mh7rLY9npucmlm8DaHdaGwFxeNW4ZnTHBg8N3vV93OOu051yHlX8SlZwF9UwT42smBNqqd5ZnKrLA5z3uKBs0E9Bajh3Aj20VbnpK9znUbaetwP8vnjRrwgS/zCRRTi3Zp8M/ubGEtqCHQAK2yyYY19+85KfjKoqukX9b8GUk72DtlRiedfSMX4bh5cUvdeBxkIBuFtRODnZzxyVdEdP8ZbFXwPhHjm7ldzohTQRyz8IEbpU9vHJ2XEKb6v9DFMXCODDuVzqn9+jGR7Grxn/+h0Zb4HgYwaLZijtQ9pKYvqy6Sjsd+GnUW78bfNYtKYVpYo5QpHTbclmzKWILOh4XTABAVQrHXWwzxmxE9vJsFMMrB+Z0IcLoE/UoDJKV9mqP25NZXM8RN5DReSW1uR23wfkJCkmA0/7VWXtJRd/0=
  template:
    metadata:
      name: resumen-secreto
      namespace: sa-p8
    type: Opaque
